// Job DSL seed script: every application in the list below gets a build
// pipeline, so adding an app is a one-line change reviewed like any other code.
// Run it from a "seed" freestyle job with the Job DSL plugin.

def repo = 'https://github.com/example-org/homelab-apps.git'

// name -> optional extra parameters for that app's build job
def applications = [
    'reverse-proxy'   : [],
    'metrics-exporter': [],
    'backup-runner'   : [
        [type: 'choice', name: 'TARGET', choices: ['nightly', 'weekly'], description: 'Which backup set to run'],
    ],
    'report-builder'  : [
        [type: 'string', name: 'REPORT_DATE', default: '', description: 'Date to build for (empty = today)'],
    ],
]

// apps whose container image is rebuilt on a schedule, so pinned tooling
// can't quietly go stale
def scheduledImageRebuilds = ['reverse-proxy', 'metrics-exporter']

applications.each { appName, extraParams ->
    pipelineJob("${appName}-build") {
        description("Generated by the seed job. Builds and deploys ${appName}.")

        logRotator {
            numToKeep(10)
            daysToKeep(30)
        }

        if (extraParams) {
            parameters {
                extraParams.each { p ->
                    if (p.type == 'choice') {
                        choiceParam(p.name, p.choices, p.description)
                    } else {
                        stringParam(p.name, p.default, p.description)
                    }
                }
            }
        }

        definition {
            cpsScm {
                scm {
                    git {
                        remote {
                            url(repo)
                            credentials('github-deploy-key')
                        }
                        branch('main')
                    }
                }
                scriptPath("applications/${appName}/Jenkinsfile")
                lightweight(true)
            }
        }

        if (appName in scheduledImageRebuilds) {
            properties {
                pipelineTriggers {
                    triggers {
                        cron { spec('H 3 * * 0') }   // weekly, spread by the H hash
                    }
                }
            }
        }
    }
}
